export const products = [
    {
        id: "1",
        name: "Camiseta Mescla",
        price: 28.80,
        viewPrice: "R$28,00",
        parcelamento: [3, "R$9,33"],
        parc: "50",
        color: "cinza",
        image: "https://i.imgur.com/zK5JcyT.png",
        size: ["M", "GG"],
        date: 2019 - 12 - 17
    },
    {
        id: "2",
        name: "Saia em couro",
        price: 398.00,
        viewPrice: "R$398,00",
        parcelamento: [5, "R$30,00"],
        parc: "500",
        color: "preto",
        image: "https://i.imgur.com/DukOd0S.png",
        size: ["G", "40"],
        date: 1998 - 12 - 17
    },
    {
        id: "3",
        name: "Cardigan Tigre",
        price: 398.80,
        viewPrice: "R$398,00",
        parcelamento: [5, "R$30,00"],
        parc: "500",
        color: "laranja",
        image: "https://i.imgur.com/0P0EjcN.png",
        size: ["GG", "44"],
        date: 1997 - 12 - 17
    },
    {
        id: "4",
        name: "Cardigan off white",
        price: 99.90,
        viewPrice: "R$99,00",
        parcelamento: [3, "R$30,00"],
        parc: "150",
        color: "branco",
        image: "https://i.imgur.com/WTYIFN6.png",
        size: ["U", "46"],
        date: 1996 - 12 - 17
    },
    {
        id: "5",
        name: "Body Leopardo",
        price: 129.90,
        viewPrice: "R$129,90",
        parcelamento: [3, "R$43,43"],
        parc: "150",
        color: "amarelo",
        image: "https://i.imgur.com/ghIRDhO.png",
        size: ["M"],
        date: 1999 - 12 - 17
    },
    {
        id: "6",
        name: "Casaco Pelos",
        price: 398.00,
        viewPrice: "R$398,00",
        parcelamento: [5, "R$30,00"],
        parc: "500",
        color: "rosa",
        image: "https://i.imgur.com/HCOtB9y.png",
        size: ["GG", "38"],
        date: 1999 - 12 - 16
    },
    {
        id: "7",
        name: "Cropped Stripes",
        price: 120.00,
        viewPrice: "R$120,00",
        parcelamento: [3, "R$40,00"],
        parc: "150",
        color: "amarelo",
        image: "https://i.imgur.com/ENyOegq.png",
        size: ["36", "U"],
        date: 2000 - 12 - 17
    },
    {
        id: "8",
        name: "Camisa Transparente",
        price: 60.00,
        viewPrice: "R$60,00",
        parcelamento: [3, "R$20,00"],
        parc: "50",
        color: "branco",
        image: "https://i.imgur.com/QHMKCmP.png",
        size: ["P"],
        date: 2000 - 11 - 17
    },
    {
        id: "9",
        name: "Pochete Clutch",
        price: 99.00,
        viewPrice: "R$99,00",
        parcelamento: [3, "R$33,00"],
        parc: "150",
        color: "amarelo",
        image: "https://i.imgur.com/QHMKCmP.png",
        size: ["M"],
        date: 2017 - 12 - 17
    },
    {
        id: "10",
        name: "Pochete Clutch",
        price: 90.00,
        viewPrice: "R$90,00",
        parcelamento: [3, "R$30,00"],
        parc: "150",
        color: "laranja",
        image: "https://i.imgur.com/HCOtB9y.png",
        size: ["M"],
        date: 2018 - 12 - 17
    },
    {
        id: "11",
        name: "Pochete Clutch",
        price: 99.00,
        viewPrice: "R$99,00",
        parcelamento: [3, "R$33,00"],
        parc: "150",
        color: "azul",
        image: "https://i.imgur.com/ENyOegq.png",
        size: ["M"],
        date: 1995 - 12 - 17
    },
    {
        id: "12",
        name: "Pochete Clutch",
        price: 600.00,
        viewPrice: "R$600,00",
        parcelamento: [3, "R$300,00"],
        parc: "501",
        color: "branco",
        image: "https://i.imgur.com/zK5JcyT.png",
        size: ["M"],
        date: 2020 - 12 - 17
    },
    {
        id: "13",
        name: "Pochete Clutch",
        price: 800.00,
        viewPrice: "R$800,00",
        parcelamento: [4, "R$200,00"],
        parc: "501",
        color: "cinza",
        image: "https://i.imgur.com/0P0EjcN.png",
        size: ["M"],
        date: 2021 - 12 - 17
    },
    {
        id: "14",
        name: "Pochete Clutch",
        price: 9.00,
        viewPrice: "R$9,00",
        parcelamento: [3, "R$3,00"],
        parc: "50",
        color: "verde",
        image: "https://i.imgur.com/WTYIFN6.png",
        size: ["M"],
        date: 2022 - 12 - 17
    }
]
